import { createFileRoute } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import { ArrowRight, ArrowDown, ArrowUp, ArrowUpRight, MapPin, GraduationCap, Cpu, CircuitBoard, Code2, Menu, X, Github, Award, Mail, Linkedin, Check, BookOpen } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Toaster } from '@/components/ui/sonner';
import { ContactForm } from '@/components/portfolio/contact-form';
import { PortfolioIcon, SectionHeading, SkillBadge, SocialLinks, ProjectArt } from '@/components/portfolio/elements';
import { navigation, learning, skills, projects, certificates, achievements, interests, journey, goals } from '@/lib/portfolio-data';
import chipImage from '@/assets/semiconductor-chip.jpg';
const pageTitle='Abhinav Gurjar | ECE Student | Semiconductor & Chip Design';
const description='Portfolio of Abhinav Gurjar, a B.Tech Electronics & Communication Engineering student at JECRC University, Jaipur, passionate about semiconductor technology, VLSI, digital electronics, and chip design.';
export const Route=createFileRoute('/')({head:()=>({meta:[{title:pageTitle},{name:'description',content:description},{property:'og:title',content:pageTitle},{property:'og:description',content:description},{property:'og:type',content:'website'},{property:'og:url',content:'/'},{name:'twitter:card',content:'summary_large_image'}],links:[{rel:'canonical',href:'/'}]}),component:Portfolio});
function Portfolio(){
 const [menu,setMenu]=useState(false);const [active,setActive]=useState('home');const [scrolled,setScrolled]=useState(false);const [progress,setProgress]=useState(0);const [project,setProject]=useState<number|null>(null);const [certificate,setCertificate]=useState<number|null>(null);const [interest,setInterest]=useState<number|null>(null);
 useEffect(()=>{const update=()=>{const y=window.scrollY;setScrolled(y>30);setProgress(y/Math.max(1,document.documentElement.scrollHeight-window.innerHeight));let current='home';for(const label of navigation){const element=document.getElementById(label.toLowerCase());if(element&&element.getBoundingClientRect().top<=160)current=label.toLowerCase();}setActive(current);};update();window.addEventListener('scroll',update,{passive:true});document.documentElement.classList.add('motion-ready');const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target);}},{threshold:.06});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));return()=>{window.removeEventListener('scroll',update);observer.disconnect();document.documentElement.classList.remove('motion-ready');};},[]);
 function navLinks(){return navigation.map(label=><a key={label} href={`#${label.toLowerCase()}`} className={`nav-link ${active===label.toLowerCase()?'active':''}`} aria-current={active===label.toLowerCase()?'location':undefined} onClick={()=>setMenu(false)}>{label}</a>);}
 const selectedProject=project===null?undefined:projects[project]; const selectedCertificate=certificate===null?undefined:certificates[certificate];
 return <><a href="#main" className="skip-link">Skip to content</a><header className={`topbar ${scrolled?'scrolled':''}`}><div className="page-width nav-inner"><a className="monogram" href="#home" aria-label="Abhinav Gurjar home">A<span>G</span><span className="text-sm">.</span></a><nav className="desktop-nav" aria-label="Main navigation">{navLinks()}</nav><Button asChild variant="glass" className="nav-connect" size="sm"><a href="#contact">Let’s Connect <ArrowUpRight/></a></Button><Button variant="ghost" size="icon" className="mobile-menu-toggle" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} aria-controls="mobile-navigation" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</Button></div>{menu&&<nav id="mobile-navigation" className="mobile-nav" aria-label="Mobile navigation">{navLinks()}</nav>}<div className="scroll-track" style={{transform:`scaleX(${progress})`}} aria-hidden="true"/></header>
 <main id="main"><section id="home" className="hero"><div className="page-width"><div className="hero-grid"><div className="hero-copy"><div className="status"><span className="status-dot"/>Currently Exploring: VLSI & Digital Design</div><h1>Abhinav<br/><span>Gurjar.</span></h1><div className="hero-subtitle">B.Tech ECE Student <span className="px-1">|</span><br className="hidden sm:block"/><span>Semiconductor & Chip Design Enthusiast</span></div><div className="hero-location"><MapPin size={13}/> JECRC University, Jaipur</div><p className="hero-description">I’m a first-year Electronics & Communication Engineering student passionate about semiconductor technology, digital electronics, programming, and the fascinating world of chip design.</p><div className="flex flex-wrap gap-3"><Button asChild variant="glow"><a href="#projects">Explore My Work <ArrowUpRight/></a></Button><Button asChild variant="glass"><a href="#contact">Get In Touch <ArrowRight/></a></Button></div><SocialLinks/></div><div className="hero-visual"><img className="chip-image" src={chipImage} width={1024} height={1024} alt="Modern semiconductor chip with illuminated blue and cyan circuit connections" fetchPriority="high"/><div className="chip-label">DIGITAL SYSTEMS<br/>ENDLESS POSSIBILITIES</div><div className="chip-caption">FROM CURIOSITY TO CIRCUITS</div></div></div><div className="hero-bottom"><div className="hero-fields"><span><GraduationCap size={13}/> B.Tech ECE · 2026–2030</span><span><Cpu size={12}/> Semiconductor Technology</span><span><CircuitBoard size={12}/> Designing the future, bit by bit.</span></div><a className="scroll-hint" href="#about">Scroll to explore <ArrowDown size={13}/></a></div></div></section>
 <section id="about" className="section section-tinted"><div className="page-width reveal"><SectionHeading number="01" label="A little about me" title="Curiosity. Circuits." accent="Possibilities."/><div className="about-layout"><div className="body-copy"><p>I’m <strong>Abhinav Gurjar</strong>, a first-year B.Tech Electronics & Communication Engineering student at <strong>JECRC University, Jaipur</strong>. I’m deeply interested in semiconductor technology and chip designing, and I’m currently building a strong foundation in electronics, programming, digital logic, and computer engineering.</p><p>I enjoy understanding how electronic systems work, from fundamental semiconductor devices and logic gates to the architecture behind modern integrated circuits. My goal is to continuously improve my technical skills and eventually contribute to the development of advanced semiconductor and chip-design technologies.</p></div><div><div className="mini-label mb-4 flex items-center gap-2"><BookOpen size={14} className="text-primary"/> Currently Learning</div><div className="badges">{learning.map(item=><SkillBadge key={item} item={item}/>)}</div></div></div><div className="highlights">{[['Electronics Enthusiast','Exploring electronic circuits, devices, and digital systems.','circuit'],['Chip Design Aspirant','Building foundational knowledge in VLSI, RTL, and digital IC design.','chip'],['Continuous Learner','Learning programming and engineering technologies through projects and practice.','book']].map(([title,copy,icon],i)=><article key={title} className={`panel tone-${i===1?'cyan':i===2?'violet':'blue'}`}><div className="icon-box"><PortfolioIcon name={icon}/></div><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
 <section id="education" className="section"><div className="page-width reveal"><SectionHeading number="02" label="Academic foundation" title="Learning with" accent="purpose."/><div className="timeline"><article className="timeline-item"><div className="timeline-dot"/><div className="timeline-top"><h3>B.Tech — Electronics & Communication Engineering</h3><span className="year">2026 — 2030</span></div><p>JECRC University, Jaipur, Rajasthan</p><div className="flex flex-wrap gap-2 my-4"><span className="tag">First Year</span><span className="tag">Semiconductor Technology & Chip Designing</span></div><div className="mini-label mb-3">Relevant areas of study</div><div className="badges">{['Engineering Mathematics','Engineering Physics','Basic Electrical Engineering','Electronic Devices','Digital Electronics','Programming Fundamentals','Communication Engineering Fundamentals'].map(item=><SkillBadge key={item} item={item}/>)}</div></article><article className="timeline-item"><div className="timeline-dot"/><div className="timeline-top"><h3>Senior Secondary Education</h3><span className="year">2024 — 2026</span></div><p>Science Stream — Physics, Chemistry & Mathematics</p><p className="mt-3 max-w-3xl">Developed a strong foundation in mathematics, physics, analytical reasoning, and problem solving, providing a foundation for engineering studies.</p></article></div></div></section>
 <section id="skills" className="section section-tinted"><div className="page-width reveal"><SectionHeading number="03" label="My growing toolkit" title="Foundations for the" accent="future." description="A developing toolkit, built through curiosity, coursework, and hands-on practice."/><div className="skills-grid">{skills.map(category=><article className="panel" key={category.title}><div className="icon-box"><PortfolioIcon name={category.icon}/></div><h3>{category.title}</h3><div className="badges">{category.items.map(item=><SkillBadge key={item} item={item}/>)}</div></article>)}</div></div></section>
 <section id="projects" className="section"><div className="page-width reveal"><SectionHeading number="04" label="Putting knowledge into practice" title="Small projects." accent="Big learnings." description="Exploring the intersection of electronics, digital design, and code — one project at a time."/><div className="projects-grid">{projects.map((item,i)=><article className="panel project-card" key={item.title}><div className="project-art"><span className="project-number">PROJECT / 0{i+1}</span><span className="tag project-art-tag">{item.category}</span><ProjectArt type={item.art}/></div><div className="project-content"><h3>{item.title}</h3><p>{item.description}</p><div className="badges">{item.technologies.map(tech=><SkillBadge key={tech} item={tech}/>)}</div><div className="project-actions"><Button variant="glass" onClick={()=>setProject(i)}>{item.action}<ArrowUpRight/></Button><Button variant="ghost" disabled title="Repository URL not provided"><Github/> GitHub</Button></div></div></article>)}</div></div></section>
 <section id="certifications" className="section section-tinted"><div className="page-width reveal"><SectionHeading number="05" label="Beyond the classroom" title="Always" accent="learning." description="Foundational courses in programming, electronics, and semiconductor technology."/><div className="cert-grid">{certificates.map(([name,issuer],i)=><article className="panel" key={name}><div className="icon-box"><Award size={18}/></div><h3>{name}</h3><p>{issuer}</p><span className="year">2026</span><Button variant="glass" onClick={()=>setCertificate(i)}>View Certificate<ArrowUpRight/></Button></article>)}</div></div></section>
 <section id="achievements" className="section"><div className="page-width reveal"><SectionHeading number="06" label="Progress worth celebrating" title="Every step" accent="counts."/><div className="achievements-grid">{achievements.map(([title,copy,icon])=><article className="panel" key={title}><div className="icon-box"><PortfolioIcon name={icon}/></div><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></div></section>
 <section id="semiconductors" className="section section-tinted"><div className="page-width reveal"><SectionHeading number="07" label="The technology that inspires me" title="Why Semiconductor" accent="& Chip Design?"/><div className="about-layout body-copy"><p>Almost every modern technology depends on semiconductors. From smartphones and computers to artificial intelligence, automobiles, and communication systems, integrated circuits are at the heart of today’s technological world.</p><p>My interest in semiconductor and chip design comes from wanting to understand how complex electronic systems are built from fundamental devices, logic, and architecture. I want to develop a strong foundation in digital design, VLSI, computer architecture, and semiconductor technology and gradually progress toward designing efficient and innovative hardware systems.</p></div><div className="interest-grid">{interests.map(([title],i)=><Button key={title} variant="ghost" className="interest-card" aria-expanded={interest===i} aria-controls="interest-details" onClick={()=>setInterest(interest===i?null:i)}><PortfolioIcon name={['chip','circuit','code','terminal'][i]}/><span>{title}</span><ArrowUpRight className="self-end"/></Button>)}</div><div id="interest-details" className="interest-details" aria-live="polite">{interest!==null&&interests[interest]?.[1]}</div></div></section>
 <section id="journey" className="section"><div className="page-width reveal"><SectionHeading number="08" label="A roadmap, not a race" title="My Learning" accent="Journey" description="Building strong fundamentals today to design better technology tomorrow." centered/><div className="journey-grid">{journey.map((title,i)=><article className={`journey-step ${i>2?'future':''}`} key={title}><span className="step-number">0{i+1} <span className="ml-2">{i<7?'→':''}</span></span><h3>{title}</h3><p>{i<=2?'Building foundations':'On the horizon'}</p></article>)}</div></div></section>
 <section id="goals" className="section section-tinted"><div className="page-width reveal"><SectionHeading number="09" label="Looking ahead" title="My" accent="Goals"/><div className="goals-grid">{goals.map(([title,copy],i)=><article className="panel" key={title}><div className="step-number">0{i+1} / {['THE FOUNDATION','THE PRACTICE','THE VISION'][i]}</div><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
 <section id="contact" className="section"><div className="page-width reveal"><SectionHeading number="10" label="Good things start with a conversation" title="Let’s" accent="Connect."/><div className="contact-grid"><div className="contact-copy"><p>I’m always open to learning, collaborating on interesting projects, and connecting with people who share an interest in electronics, semiconductors, programming, and technology.</p>{[{label:'Email',text:'abhinav.mandawar45@gmail.com',href:'mailto:abhinav.mandawar45@gmail.com',Icon:Mail},{label:'GitHub',text:'github.com/abhinav-gurjar',href:'https://github.com/abhinav-gurjar',Icon:Github},{label:'LinkedIn',text:'linkedin.com/in/abhinav-gurjar',href:'https://www.linkedin.com/in/abhinav-gurjar',Icon:Linkedin}].map(({label,text,href,Icon})=><a key={label} className="contact-link" href={href} target={label==='Email'?undefined:'_blank'} rel={label==='Email'?undefined:'noopener noreferrer'}><div className="icon-box"><Icon size={16}/></div><div><small>{label}</small><p>{text}</p></div><ArrowUpRight size={14}/></a>)}</div><ContactForm/></div></div></section></main>
 <footer className="footer"><div className="page-width"><div className="footer-main"><div><div className="footer-name">Abhinav Gurjar<span className="text-primary">.</span></div><div className="footer-sub">B.Tech ECE | Semiconductor & Chip Design Enthusiast</div></div><nav className="footer-nav" aria-label="Footer navigation">{['Home','About','Projects','Contact'].map(label=><a href={`#${label.toLowerCase()}`} key={label}>{label}</a>)}</nav><SocialLinks/></div><div className="footer-end"><span>© 2026 Abhinav Gurjar. All Rights Reserved.</span><span>Curiosity today. Innovation tomorrow.</span></div></div></footer>
 {scrolled&&<Button variant="glass" size="icon" className="back-top" aria-label="Back to top" title="Back to top" onClick={()=>window.scrollTo({top:0,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}><ArrowUp/></Button>}
 <Dialog open={selectedProject!==undefined} onOpenChange={open=>{if(!open)setProject(null);}}><DialogContent className="bg-card border-border"><DialogHeader><DialogTitle>{selectedProject?.title}</DialogTitle><DialogDescription>{selectedProject?.description}</DialogDescription></DialogHeader><div className="mini-label">Project features</div><ul className="space-y-2">{selectedProject?.features.map(feature=><li key={feature} className="flex items-center gap-2 text-sm text-muted-foreground"><Check size={14} className="text-cyan"/>{feature}</li>)}</ul><p className="text-xs text-muted-foreground border-t border-border pt-4">A live project URL and GitHub repository have not been provided yet.</p></DialogContent></Dialog>
 <Dialog open={selectedCertificate!==undefined} onOpenChange={open=>{if(!open)setCertificate(null);}}><DialogContent className="bg-card border-border"><DialogHeader><DialogTitle>{selectedCertificate?.[0]}</DialogTitle><DialogDescription>{selectedCertificate?.[1]} · 2026</DialogDescription></DialogHeader><div className="icon-box"><Award/></div><p className="text-sm text-muted-foreground">The certificate file hasn’t been added yet. No verification link or certificate ID is available.</p></DialogContent></Dialog><Toaster position="bottom-right" theme="dark"/></>;
}
