import { useState, type FormEvent } from 'react';
import { Send, LoaderCircle } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { sendContactMessage } from '@/lib/contact.functions';
export function ContactForm(){
 const [errors,setErrors]=useState<Record<string,string>>({}); const [sending,setSending]=useState(false);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault(); const form=event.currentTarget; const values=new FormData(form); const data={name:String(values.get('name')??'').trim(),email:String(values.get('email')??'').trim(),subject:String(values.get('subject')??'').trim(),message:String(values.get('message')??'').trim(),website:String(values.get('website')??'')}; const next:Record<string,string>={}; if(data.name.length<2)next.name='Please enter at least 2 characters.';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email))next.email='Please enter a valid email address.';if(data.subject.length<3)next.subject='Please enter at least 3 characters.';if(data.message.length<10)next.message='Please enter a message of at least 10 characters.';setErrors(next);if(Object.keys(next).length){form.querySelector<HTMLElement>(`#contact-${Object.keys(next)[0]}`)?.focus();return;} setSending(true);try{await sendContactMessage({data});toast.success('Message received!',{description:'Your message has been securely saved. Thank you for reaching out.'});form.reset();}catch(error){toast.error(error instanceof Error?error.message:'Unable to send. Please try the email link.');}finally{setSending(false);}}
 function field(name:string,label:string,placeholder:string,type='text'){return <div className="field"><label htmlFor={`contact-${name}`}>{label}</label><input id={`contact-${name}`} name={name} type={type} placeholder={placeholder} maxLength={name==='email'?254:name==='subject'?150:100} autoComplete={name==='name'?'name':name==='email'?'email':'off'} aria-required="true" aria-invalid={Boolean(errors[name])} aria-describedby={errors[name]?`${name}-error`:undefined}/>{errors[name]&&<div className="field-error" id={`${name}-error`} role="alert">{errors[name]}</div>}</div>}
 return <form className="contact-form" onSubmit={submit} noValidate><div className="form-row">{field('name','Name','Your name')}{field('email','Email','you@example.com','email')}</div>{field('subject','Subject',"What’s on your mind?")}<div className="field"><label htmlFor="contact-message">Message</label><textarea id="contact-message" name="message" placeholder="Let’s build something interesting..." maxLength={5000} aria-required="true" aria-invalid={Boolean(errors.message)} aria-describedby={errors.message?'message-error':undefined}/>{errors.message&&<div id="message-error" className="field-error" role="alert">{errors.message}</div>}</div><div className="honeypot" aria-hidden="true"><label htmlFor="website">Website</label><input id="website" name="website" tabIndex={-1} autoComplete="off"/></div><Button variant="glow" type="submit" disabled={sending}>{sending?<LoaderCircle className="animate-spin"/>:<Send/>}{sending?'Sending...':'Send Message'}</Button><p className="form-note">Your message is saved securely. You can also reach me directly by email.</p></form>;
}
