import { useState, type FormEvent } from 'react';
import { Send } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
const CONTACT_EMAIL='abhinav.gurjar@gmail.com';
export function ContactForm(){
 const [errors,setErrors]=useState<Record<string,string>>({});
 function submit(event:FormEvent<HTMLFormElement>){event.preventDefault(); const form=event.currentTarget; const values=new FormData(form); const data={name:String(values.get('name')??'').trim().slice(0,100),email:String(values.get('email')??'').trim().slice(0,254),subject:String(values.get('subject')??'').trim().slice(0,150),message:String(values.get('message')??'').trim().slice(0,5000)}; const next:Record<string,string>={}; if(data.name.length<2)next['name']='Please enter at least 2 characters.';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email))next['email']='Please enter a valid email address.';if(data.subject.length<3)next['subject']='Please enter at least 3 characters.';if(data.message.length<10)next['message']='Please enter a message of at least 10 characters.';setErrors(next);if(Object.keys(next).length){form.querySelector<HTMLElement>(`#contact-${Object.keys(next)[0]}`)?.focus();return;}
  const body=`${data.message}\n\n— ${data.name} (${data.email})`;
  window.location.href=`mailto:${CONTACT_EMAIL}?subject=${encodeURIComponent(data.subject)}&body=${encodeURIComponent(body)}`;
  toast.success('Opening your email app...',{description:'Your message is ready to send.'});}
 function field(name:string,label:string,placeholder:string,type='text'){return <div className="field"><label htmlFor={`contact-${name}`}>{label}</label><input id={`contact-${name}`} name={name} type={type} placeholder={placeholder} maxLength={name==='email'?254:name==='subject'?150:100} autoComplete={name==='name'?'name':name==='email'?'email':'off'} aria-required="true" aria-invalid={Boolean(errors[name])} aria-describedby={errors[name]?`${name}-error`:undefined}/>{errors[name]&&<div className="field-error" id={`${name}-error`} role="alert">{errors[name]}</div>}</div>}
 return <form className="contact-form" onSubmit={submit} noValidate><div className="form-row">{field('name','Name','Your name')}{field('email','Email','you@example.com','email')}</div>{field('subject','Subject',"What’s on your mind?")}<div className="field"><label htmlFor="contact-message">Message</label><textarea id="contact-message" name="message" placeholder="Let’s build something interesting..." maxLength={5000} aria-required="true" aria-invalid={Boolean(errors['message'])} aria-describedby={errors['message']?'message-error':undefined}/>{errors['message']&&<div id="message-error" className="field-error" role="alert">{errors['message']}</div>}</div><Button variant="glow" type="submit"><Send/>Send Message</Button><p className="form-note">This opens your email app with your message ready to send.</p></form>;
}
