import { Cpu, Code2, CircuitBoard, Terminal, Users, GraduationCap, Lightbulb, BookOpen, Award, ArrowUpRight, Github, Linkedin, Mail } from 'lucide-react';
export function PortfolioIcon({name,className='size-4'}:{name:string|undefined;className?:string}) { const icons:Record<string,typeof Cpu>={chip:Cpu,code:Code2,circuit:CircuitBoard,terminal:Terminal,people:Users,education:GraduationCap,idea:Lightbulb,book:BookOpen,workshop:Award}; const Icon=icons[name??'chip']??Cpu; return <Icon className={className} aria-hidden="true"/>; }
export function SectionHeading({number,label,title,accent,description,centered=false}:{number:string;label:string;title:string;accent?:string;description?:string;centered?:boolean}) { return <div className={`section-heading ${centered?'centered':''}`}><div className="eyebrow">{number} / {label}</div><h2>{title} {accent&&<span>{accent}</span>}</h2>{description&&<p>{description}</p>}</div>; }
export function SkillBadge({item}:{item:string}) { const [label,level]=item.split('|'); return <span className="skill-badge" tabIndex={0} title={level?`${label}: ${level}`:label}>{label}{level&&<small>{level}</small>}</span>; }
export function SocialLinks() { return <div className="social-links"><span className="social-separator"/><a href="https://github.com/abhinav-gurjar" target="_blank" rel="noopener noreferrer" aria-label="Abhinav on GitHub" title="GitHub"><Github size={17}/></a><a href="https://www.linkedin.com/in/abhinav-gurjar" target="_blank" rel="noopener noreferrer" aria-label="Abhinav on LinkedIn" title="LinkedIn"><Linkedin size={17}/></a><a href="mailto:abhinav.mandawar45@gmail.com" aria-label="Email Abhinav" title="Email"><Mail size={17}/></a></div>; }
export function ProjectArt({type}:{type:string}) { return <svg viewBox="0 0 340 150" fill="none" role="img" aria-label={`${type} project schematic`}>
 {type==='logic'?<><path d="M25 42H110M25 107H110M200 75H307" stroke="currentColor" strokeWidth="1.5"/><path d="M110 26H145C218 26 218 124 145 124H110Z" stroke="currentColor" strokeWidth="2"/><circle cx="26" cy="42" r="11" fill="var(--secondary)" stroke="currentColor"/><circle cx="26" cy="107" r="11" fill="var(--secondary)" stroke="currentColor"/><circle cx="308" cy="75" r="11" fill="var(--primary)"/><text x="22" y="46" fontSize="12" fill="var(--foreground)">1</text><text x="22" y="111" fontSize="12" fill="var(--foreground)">0</text><text x="135" y="80" fontFamily="monospace" fontSize="17" fill="currentColor">AND</text></>:type==='alu'?<><path d="M35 42H120M35 108H120M220 75H305M170 125V145" stroke="currentColor"/><path d="M120 18 162 18 170 37 178 18 220 18V125H120Z" stroke="currentColor" strokeWidth="2"/><text x="147" y="79" fill="currentColor" fontFamily="monospace" fontSize="21">ALU</text><text x="140" y="104" fill="var(--muted-foreground)" fontSize="9">4-BIT / RTL</text><text x="39" y="35" fill="var(--muted-foreground)" fontSize="10">A [3:0]</text><text x="39" y="101" fill="var(--muted-foreground)" fontSize="10">B [3:0]</text></>:type==='arduino'?<><rect x="77" y="20" width="184" height="112" rx="7" fill="var(--secondary)" stroke="var(--cyan)"/><rect x="135" y="56" width="60" height="43" rx="3" stroke="var(--cyan)"/><path d="M77 55H50V95H77M261 55H291V95H261" stroke="var(--cyan)"/><text x="143" y="84" fill="var(--cyan)" fontSize="14" fontFamily="monospace">24°C</text>{Array.from({length:10},(_,i)=><g key={i}><rect x={93+i*15} y="26" width="7" height="10" fill="var(--cyan)"/><rect x={93+i*15} y="116" width="7" height="10" fill="var(--cyan)"/></g>)}</>:<><rect x="55" y="16" width="235" height="123" rx="5" fill="var(--secondary)" stroke="currentColor"/><path d="M55 39H290" stroke="currentColor"/><circle cx="66" cy="28" r="2" fill="var(--primary)"/><circle cx="75" cy="28" r="2" fill="var(--cyan)"/><text x="73" y="60" fill="currentColor" fontFamily="monospace" fontSize="10">SEMICONDUCTOR / LEARNING HUB</text>{[0,1,2].map(i=><g key={i}><rect x={74+i*69} y="74" width="60" height="48" rx="3" stroke="var(--border)"/><path d={`M${84+i*69} 87h16m-16 9h37m-37 9h27`} stroke={i===1?'var(--cyan)':'currentColor'}/></g>)}</>}
 </svg>; }
export function ExternalArrow(){return <ArrowUpRight size={14}/>}
